import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./theme-config.css";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import NavbarPage from "./NavbarPage";
import { Theme } from "@radix-ui/themes";
import AuthProvider from "./auth/Provider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Issue Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <AuthProvider>
          <Theme accentColor="iris" grayColor="mauve">
            <NavbarPage />
            <main className="p-5">{children}</main>
          </Theme>
        </AuthProvider>
      </body>
    </html>
  );
}
